export const FONT_GROUPS = {
  Sans: [
    "Inter",
    "Poppins",
    "Montserrat",
    "Roboto",
    "Open Sans",
    "Lato",
    "Nunito",
    "Manrope",
    "DM Sans",
    "Work Sans",
    "Quicksand",
    "Raleway",
    "Oswald",
    "Mulish",
    "Comfortaa",
    "Cabin",
    "IBM Plex Sans",
    "Barlow",
    "Urbanist",
    "Outfit",
  ],
  Serif: [
    "Playfair Display",
    "Merriweather",
    "Libre Baskerville",
    "Crimson Text",
    "Cormorant",
    "EB Garamond",
    "Spectral",
    "Source Serif 4",
    "Lora",
    "Gelasio",
    "Bitter",
    "Sora",
    "Domine",
    "Bodoni Moda",
    "Fraunces",
    "Zilla Slab",
    "Noto Serif",
    "Kaisei Tokuriki",
  ],
  Display: [
    "Bebas Neue",
    "Anton",
    "Abril Fatface",
    "Pacifico",
    "Lobster",
    "Fredoka One",
    "Righteous",
    "Rubik Mono One",
    "Caveat",
    "Bangers",
    "Gripen",
    "Titan One",
    "Permanent Marker",
    "Great Vibes",
    "Dancing Script",
    "Playfair Display",
    "Bitter",
    "Press Start 2P",
    "Indie Flower",
    "Montserrat Alternates",
  ],
  Mono: [
    "JetBrains Mono",
    "Fira Code",
    "IBM Plex Mono",
    "Source Code Pro",
    "Courier Prime",
    "Roboto Mono",
    "Space Mono",
    "Inconsolata",
    "Overpass Mono",
    "Victor Mono",
  ],
} as const;

export type FontGroup = keyof typeof FONT_GROUPS;
export type FontName =
  (typeof FONT_GROUPS)[FontGroup][number];
